version: "3.4"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka
    ports:
      - 9092:9092
    restart: always
    volumes:
      - kafka_data:/bitnami
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./databases/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  sql:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 1433:1433
    volumes:
      - ./databases/sql/data:/var/opt/mssql/data
      - ./databases/sql/log:/var/opt/mssql/log
      - ./databases/sql/secrets:/var/opt/mssql/secrets
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin98sql
      - MSSQL_PID=Express

  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./databases/postgresql:/var/lib/postgresql/data
    environment:
      # - POSTGRES_USER=admin # default POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=admin


volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
